---
layout: post
title: "Breve análise sobre as notas da série Sense8 no IMDB"
published: true
tags: [htmlwidgets, plotly, r]
---

A maioria dos fãs de séries de TV possuem uma opinião sobre as séries que já assistiram, e através do IMDB (plataforma que permite aos seus usuários dar notas para filmes e séries) é possível compartilhar essa opinião e agrega-la à dos outros usuários do site para formar uma avaliação colaborativa.

Muitos fãs vêem na plataforma uma maneira de, através das notas atribuídas, descobrir _boas_ séries para assistir. Contudo, __realmente é possível confiar cegamente nas notas do IMDB?__ Essa é a pergunta que iremos responder nessa análise.

No gráfico abaixo podemos ver a evolução do _rating_ dos usuários para a série Sense8 ao longo de suas duas temporadas. O tamanho dos pontos representa a quantidade de votos que os usuários do IMDB deram para aquele respectivo episódio, ainda é possível obter informações mais detalhadas sobre o episódio passando o mouse sobre o ponto.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library('tidyverse')
library('plotly')


series = read_csv(file = "dados/series_from_imdb.csv") %>% 
  select(series_name, series_ep, season, season_ep, Episode, UserRating, UserVotes) %>% 
  filter(series_name %in% c("Black Mirror", "13 Reasons Why", "Sense8", "Stranger Things", "Mr Robot")) %>% group_by(series_name)


sense8 <- series %>% filter(series_name %in% c("Sense8"))

maxRow = sense8[which.max(sense8$UserRating),]
minRow = sense8[which.min(sense8$UserRating),]

 
 maxAndMin <- rbind(minRow, maxRow)
 
 a1 = list(
  x = maxAndMin$season_ep,
  y = maxAndMin$UserRating,
  text = c("Pior episodio", "Melhor episodio"),
  xref = "x",
  yref = "y",
  ax = 30,
  showarrow = TRUE,
 arrowhead = 2,
 arrowsize = .5,
 font = list(family = "bank gothic", size = 18),
 xanchor = "left"
 )
 
 
 l <- list(
   x = 0.85,
   y = 0.1,
  font = list(
    family = "bank gothic",
    size = 20,
    color = "#000"),
  bgcolor = "white",
  bordercolor = "white",
  borderwidth = 1)


 p1 <- plot_ly(
   data = sense8 %>% mutate(season = paste("Temporada", season)),
   x = ~season_ep,
   y = ~UserRating,
   type = "scatter",
   mode = "lines+markers",
   marker = list(size = ~UserVotes/130),
   color = ~as.character(season),
   colors = "Set1",
   text = ~paste("<b>Episodio",season_ep, "</b><br>" , Episode, "<br>Nota: ", UserRating, "<br>Total de votos:", UserVotes),
   hoverinfo = "text"
 ) %>%
 layout(
   autosize = F,
   title = "Notas dos usuários do IMDB para os episódios de Sense8<br>",
   xaxis = list(title = "Episódio da Temporada"),
   yaxis = list(title = "Rating dos usuários"),
   legend = l,
   annotations = a1
 )
 
 p1
```


À primeira vista muitos pensariam que a série evoluiu em qualidade e a segunda temporada foi um sucesso muito maior do que a primeira. Contudo, analisando com cuidado percebemos que existe uma clara relação entre a quantidade de votos dados pelos usuários e a nota do episódio (Episódios mais votados tendem a ter a nota menor). Isso fica ainda mais claro quando percebemos que o _pior_ episódio de toda a série foi o mais votado e o _melhor_ episódio foi o menos votado.

Para _amarrar_ ainda mais essa hipótese, podemos calcular a correlação entre o número de votos e o _rating_ dos episódios e ponderar sobre o valor que obtivermos.
cor(sense8$UserVotes, sense8$UserRating)
__Em português:__ A correlação é uma medida que pode variar de -1 a 1, se o valor for próximo de 1, podemos chegar a conclusão de que o número de votos aumenta juntamente com o _rating_, se o valor for próximo de -1 concluímos que conforme o número de votos aumenta o _rating_ __diminui.__ Portanto, como o valor obtido foi de __-0.6893093__ podemos inferir que de fato o número de votos dados contribui significativamente para notas menores.

<h3>Conclusão</h3>
O IMDB é uma ótima ferramenta para fãs de séries, porém, __não podemos confiar totalmente nas notas apresentadas no site pois as análises de algumas séries/filmes podem ser enviezadas pela quantidade de votos__. Mas porque isso acontece? No caso de Sense8 a hipótese que eu acredito é que a primeira temporada provavelmente decepcionou muitos fãs e devido a isso apenas os fãs mais aguerridos assistiram/votaram nos episódios da segunda temporada, causando um aumento nas notas dos episódios.
